import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar'
// import Request from '@/compnents/Request'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BeTheBond",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
        {children}
        {/* <Request/> */}
        </body>
    </html>
  );
}
